PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'author',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS registrations (id TEXT PRIMARY KEY,name TEXT NOT NULL,team_size INTEGER NOT NULL,class_grade TEXT NOT NULL,section TEXT,mobile TEXT NOT NULL,email TEXT NOT NULL,events TEXT NOT NULL,details TEXT,status TEXT NOT NULL DEFAULT 'PENDING',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tickets (id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,registration_id TEXT,category TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_reg_created ON registrations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ticket_created ON tickets(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_expiry ON sessions(expires_at);
