const CORS={'Access-Control-Allow-Origin':'https://robokriti.site','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const enc=new TextEncoder();const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sha256(s){return crypto.subtle.digest('SHA-256',enc.encode(s))}
async function verifyPassword(password,stored){const [scheme,it,salt,hash]=stored.split('$');if(scheme!=='pbkdf2')return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(atob(salt.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),iterations:Number(it),hash:'SHA-256'},key,256);return b64(bits)===hash}
async function token(secret,user){const raw=`${user.id}.${Date.now()}.${crypto.randomUUID()}`;const key=await crypto.subtle.importKey('raw',enc.encode(secret),'HMAC',false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(raw));return `${raw}.${b64(sig)}`}
async function auth(req,env){const c=req.headers.get('Cookie')||'';const m=c.match(/rk_session=([^;]+)/);if(!m)return null;const t=m[1];const h=await sha256(t);const hash=b64(h);const row=await env.DB.prepare('SELECT users.id,users.email,users.role,users.active FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND sessions.expires_at>? AND users.active=1').bind(hash,Date.now()).first();return row||null}
async function mail(env,to,subject,text){if(!env.RESEND_API_KEY||!env.MAIL_FROM)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.MAIL_FROM,to:[to],subject,text})})}
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const u=new URL(req.url);try{
if(u.pathname==='/api/auth/login'&&req.method==='POST'){const {email,password}=await req.json();const user=await env.DB.prepare('SELECT * FROM users WHERE email=? AND active=1').bind(email.toLowerCase()).first();if(!user||!(await verifyPassword(password,user.password_hash)))return json({error:'Invalid credentials'},401);const t=await token(env.SESSION_SECRET,user);const h=b64(await sha256(t));await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(h,user.id,Date.now()+1000*60*60*8).run();return new Response(JSON.stringify({ok:true}),{headers:{...CORS,'Content-Type':'application/json','Set-Cookie':`rk_session=${t}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`}})}
if(u.pathname==='/api/auth/logout'){const c=req.headers.get('Cookie')||'';const m=c.match(/rk_session=([^;]+)/);if(m){const h=b64(await sha256(m[1]));await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(h).run()}return new Response(JSON.stringify({ok:true}),{headers:{...CORS,'Content-Type':'application/json','Set-Cookie':'rk_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'}})}
if(u.pathname==='/api/registrations'&&req.method==='POST'){const p=await req.json();if(!p.name||!p.email||!p.mobile||!p.events?.length)return json({error:'Please complete all required fields.'},400);const id=`RK-${Date.now().toString(36).toUpperCase()}`;await env.DB.prepare('INSERT INTO registrations(id,name,team_size,class_grade,section,mobile,email,events,details) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,p.name,Number(p.team_size||1),p.class_grade,p.section||'',p.mobile,p.email,JSON.stringify(p.events),p.details||'').run();await mail(env,p.email,'RoboKriti 2026 registration received',`Your registration ${id} has been received. Our authorised team will review it.`);if(env.AUTHOR_EMAIL)await mail(env,env.AUTHOR_EMAIL,`New RoboKriti registration ${id}`,`New registration from ${p.name} (${p.email}).`);return json({ok:true,id},201)}
if(u.pathname==='/api/help'&&req.method==='POST'){const p=await req.json();if(!p.name||!p.email||!p.message)return json({error:'Please complete the required fields.'},400);const id=`HELP-${Date.now().toString(36).toUpperCase()}`;await env.DB.prepare('INSERT INTO tickets(id,name,email,registration_id,category,message) VALUES(?,?,?,?,?,?)').bind(id,p.name,p.email,p.registration_id||'',p.category||'General',p.message).run();await mail(env,p.email,'RoboKriti support request received',`Your support ticket is ${id}.`);if(env.AUTHOR_EMAIL)await mail(env,env.AUTHOR_EMAIL,`New RoboKriti help ticket ${id}`,`New ticket from ${p.name} (${p.email}).`);return json({ok:true,id},201)}
if(u.pathname==='/api/author/overview'&&req.method==='GET'){const user=await auth(req,env);if(!user)return json({error:'Unauthorized'},401);const registrations=(await env.DB.prepare('SELECT id,name,email,status,created_at FROM registrations ORDER BY created_at DESC LIMIT 50').all()).results;const tickets=(await env.DB.prepare('SELECT id,name,email,status,created_at FROM tickets ORDER BY created_at DESC LIMIT 50').all()).results;return json({user,registrations,tickets})}
return json({error:'Not found'},404)}catch(e){return json({error:'Server error'},500)}}};
